### ISSUE TITLE
Remove Tight UI Coupling

### ISSUE THREAD

**Issue by ryanwischkaemper** [Jaykul/PoshConsole#9]
@Jaykul  First off, I can't thank you enough for your work on this project. The examples and documentation on custom PS Host implementations are sparse, especially for WPF (everyone seems to like WinForms..).

I'm integrating PoshConsole into a WPF app I'm working on - I'm able to get a `PoshConsole` instance working and outputting to an `ItemsControl`. I'm using a MVVM framework, though, and I can't figure out how to call `PoshConsole.InvokeAsync("script.ps1")` from my view model because it has no knowledge of the `PoshConsole` instance living in the view. It's important for view models in my app to have no reference to the view or it's controls (testability, keeping business logic separate, etc).

What would be ideal is being able to instantiate instances of `PoshConsole` from view models (or any non-view-bound class) and then from there the output of `PoshConsole.InvokeAsync` could be pushed to the view. In this particular case, I don't even need to send input to the `PoshConsole` - all my Powershell scripts are written and I just need to asynchronously invoke them and bind the output to the view.

Would this be possible? I'm reviewing the code base now, but any input you could provide would be greatly appreciated.

**Comment by Jaykul** [comment]
Wow, I've been slacking. I'm sorry (I haven't been paying attention to github notifications).

When I started working in MVVM a few months ago I made some changes so that I could invoke from the ViewModels, so PoshConsole has a static `CurrentConsole` property that let's you invoke into the console from anywhere.

You can, in fact, also choose whether or not the output will be shown in PoshConsole or just put in your input. You'll have to let me know if that's enough for you (it was for me).
